In [2]:
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import r2_score
import pandas as pd
import numpy as np

In [38]:
#train_csv = pd.read_csv("/Users/shekhar/Desktop/Bootcamp/Revision/Homework/BlackFridayClusting/data/BlackFriday_head.csv")
test_csv = pd.read_csv("/Users/shekhar/Desktop/Bootcamp/Revision/Homework/BlackFridayClusting/data/BlackFriday.csv")
train_csv = test_csv.head(100000)

In [39]:
test_csv.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 NaN                 NaN      1422  
3                14.0                 NaN      1057  
4                 NaN                 NaN      7969

In [42]:
train_csv["Occupation"].unique()

array([10, 16, 15,  7, 20,  9,  1, 12, 17,  0,  3,  4, 11,  8, 19,  2, 18,
        5, 14, 13,  6])

In [43]:
test_csv["Occupation"].unique()


array([10, 16, 15,  7, 20,  9,  1, 12, 17,  0,  3,  4, 11,  8, 19,  2, 18,
        5, 14, 13,  6])

In [44]:
train_csv["Age"].unique()


array(['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25'],
      dtype=object)

In [45]:
test_csv["Age"].unique()

array(['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25'],
      dtype=object)

In [46]:
test_csv["Gender"].unique()

array(['F', 'M'], dtype=object)

In [47]:
test_csv["Marital_Status"].unique()

array([0, 1])

In [53]:
def find_occupation(occupation):
    switcher = {
        10:"10",
        16:"16",
        15:"15",
        7:"7",
        20:"20",
        9:"9",
        1:"1",
        12:"12",
        17:"17",
        0:"0",
        3:"3",
        4:"4",
        11:"11",
        8:"8",
        19:"19",
        2:"2",
        18:"18",
        5:"5",
        14:"14",
        13:"13",
        6:"6"
    }
    
    return switcher.get(occupation, "99")         

In [54]:
group_list = []
for index,row in test_csv.iterrows():
    if (row["Gender"]=="F" and row["Age"]=="0-17" and row["Marital_Status"]==0):
        group_number = find_occupation(row["Occupation"])
        #print(group_number)
        group_list.append(int("110" + group_number))
    elif (row["Gender"]=="F" and row["Age"]=="0-17" and row["Marital_Status"]==1):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("111" + group_number)))
    elif (row["Gender"]=="M" and row["Age"]=="0-17" and row["Marital_Status"]==0):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("210" + group_number)))
    elif (row["Gender"]=="M" and row["Age"]=="0-17" and row["Marital_Status"]==1):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("211" + group_number))) 
    elif (row["Gender"]=="F" and row["Age"]=="18-25" and row["Marital_Status"]==0):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("120" + group_number)))                          
    elif (row["Gender"]=="F" and row["Age"]=="18-25" and row["Marital_Status"]==1):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("121" + group_number)))                          
    elif (row["Gender"]=="M" and row["Age"]=="18-25" and row["Marital_Status"]==0):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("220" + group_number)))                          
    elif (row["Gender"]=="M" and row["Age"]=="18-25" and row["Marital_Status"]==1):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("221" + group_number)))                          
    elif (row["Gender"]=="F" and row["Age"]=="26-35" and row["Marital_Status"]==0):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("130" + group_number)))                          
    elif (row["Gender"]=="F" and row["Age"]=="26-35" and row["Marital_Status"]==1):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("131" + group_number)))                          
    elif (row["Gender"]=="M" and row["Age"]=="26-35" and row["Marital_Status"]==0):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("230" + group_number)))                          
    elif (row["Gender"]=="M" and row["Age"]=="26-35" and row["Marital_Status"]==1):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("231" + group_number)))       
    elif (row["Gender"]=="F" and row["Age"]=="36-45" and row["Marital_Status"]==0):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("140" + group_number)))       
    elif (row["Gender"]=="F" and row["Age"]=="36-45" and row["Marital_Status"]==1):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("141" + group_number)))       
    elif (row["Gender"]=="M" and row["Age"]=="36-45" and row["Marital_Status"]==0):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("240" + group_number))) 
    elif (row["Gender"]=="M" and row["Age"]=="36-45" and row["Marital_Status"]==1):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("241" + group_number)))    
    elif (row["Gender"]=="F" and row["Age"]=="46-50" and row["Marital_Status"]==0):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("150" + group_number)))   
    elif (row["Gender"]=="F" and row["Age"]=="46-50" and row["Marital_Status"]==1):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("151" + group_number)))  
    elif (row["Gender"]=="M" and row["Age"]=="46-50" and row["Marital_Status"]==0):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("250" + group_number)))    
    elif (row["Gender"]=="M" and row["Age"]=="46-50" and row["Marital_Status"]==1):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("251" + group_number)))  
    elif (row["Gender"]=="F" and row["Age"]=="51-55" and row["Marital_Status"]==0):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("160" + group_number))) 
    elif (row["Gender"]=="F" and row["Age"]=="51-55" and row["Marital_Status"]==1):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("161" + group_number))) 
    elif (row["Gender"]=="M" and row["Age"]=="51-55" and row["Marital_Status"]==0):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("260" + group_number)))   
    elif (row["Gender"]=="M" and row["Age"]=="51-55" and row["Marital_Status"]==1):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("261" + group_number))) 
    elif (row["Gender"]=="F" and row["Age"]=="55+" and row["Marital_Status"]==0):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("170" + group_number)))  
    elif (row["Gender"]=="F" and row["Age"]=="55+" and row["Marital_Status"]==1):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("171" + group_number)))  
    elif (row["Gender"]=="M" and row["Age"]=="55+" and row["Marital_Status"]==0):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("270" + group_number)))   
    elif (row["Gender"]=="M" and row["Age"]=="55+" and row["Marital_Status"]==1):
        group_number = find_occupation(row["Occupation"])
        group_list.append(int(str("271" + group_number)))  

In [55]:
test_csv["Group"] = pd.Series(group_list)


In [56]:
test_csv.count()

User_ID                       537577
Product_ID                    537577
Gender                        537577
Age                           537577
Occupation                    537577
City_Category                 537577
Stay_In_Current_City_Years    537577
Marital_Status                537577
Product_Category_1            537577
Product_Category_2            370591
Product_Category_3            164278
Purchase                      537577
Group                         537577
dtype: int64

In [59]:
x_train = train_csv['Group']
y_train = train_csv['Purchase']
x_test = test_csv['Group']
y_test = test_csv['Purchase']

x_train = np.array(x_train)
y_train = np.array(y_train)

x_test = np.array(x_test)
y_test = np.array(y_test)

x_train = x_train.reshape(-1,1)
x_test = x_test.reshape(-1,1)

[11010 11010 11010 ...  2204  2204  2204]


In [58]:
clf = LinearRegression(normalize=True)
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
print(r2_score(y_test,y_pred))

0.0011414671177045754


In [60]:
x_train = train_csv['Group']
y_train = train_csv['Product_Category_1']
x_test = test_csv['Group']
y_test = test_csv['Product_Category_1']

x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)

x_train = x_train.reshape(-1,1)
x_test = x_test.reshape(-1,1)

[ 3  1 12 ...  2  5  5]


In [61]:
clf = LinearRegression(normalize=True)
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
print(r2_score(y_test,y_pred))


0.0001718817194638067


NameError: name 'test_csv' is not defined